// =============================================================================
// File        : pr_controller.sv
// Project     : Supply Chain Security in 3PIP FPGA
// Author      : Kaustubh Pandey (230959054)
// Description : Dynamic Partial Reconfiguration (DPR) controller. Interfaces
//               with Xilinx ICAP/PCAP (Internal/Processor Configuration
//               Access Port) to reload a trusted "blank" module over the
//               suspected Trojan-infected IP region.
//
//               State Machine:
//               IDLE → PR_INIT → SENDING (bitstream) → VERIFY → DONE/ERROR
//
//               In a real Artix-7 design, this module drives the ICAP2_7SERIES
//               primitive. The bitstream for the blank/trusted module must be
//               pre-generated by Vivado and stored in Block RAM or Flash.
//
//               For simulation, the state machine is fully modelled; ICAP
//               interface signals are mocked via internal flags.
//
//               Reference: Xilinx XAPP1159, XAPP1222, Bucknall & Fahmy (2023)
// =============================================================================

`timescale 1ns / 1ps

module pr_controller #(
    parameter int BITSTREAM_WORDS = 256,  // Simulated bitstream length
    parameter int PR_TIMEOUT_CYC  = 4096  // Watchdog timeout cycles
) (
    input  logic        clk,
    input  logic        rst_n,
    // Trigger from alarm aggregator
    input  logic        pr_trigger,
    // Status outputs
    output logic        pr_busy,
    output logic        pr_done,
    output logic        pr_error,
    output logic [7:0]  pr_state_debug,
    // Simulated ICAP interface (tie to ICAP2_7SERIES primitive in synthesis)
    output logic        icap_csn,          // Active-low chip select
    output logic        icap_rdwrn,        // 0=write (program), 1=read
    output logic [31:0] icap_din,          // Data to FPGA configuration logic
    input  logic        icap_avail         // ICAP ready (tie HIGH in simulation)
);

    // ---- State encoding ----------------------------------------------------
    typedef enum logic [2:0] {
        IDLE      = 3'd0,
        PR_INIT   = 3'd1,
        SENDING   = 3'd2,
        VERIFY    = 3'd3,
        PR_DONE   = 3'd4,
        PR_ERROR  = 3'd5
    } pr_state_t;

    pr_state_t state, next;

    // ---- Datapath registers ------------------------------------------------
    logic [$clog2(BITSTREAM_WORDS)-1:0] word_cnt;
    logic [$clog2(PR_TIMEOUT_CYC)-1:0]  timeout_cnt;
    logic                               timeout;

    // Simulated bitstream ROM (blank/NOP pattern)
    // In hardware: read from BRAM pre-loaded at boot
    function automatic logic [31:0] get_bitstream_word(input int idx);
        // Real bitstream: sync word + frame addresses + NOP commands
        case (idx)
            0:       return 32'hAA995566;  // Sync word
            1:       return 32'h20000000;  // NOP
            2:       return 32'h30008001;  // Write CTRL0 register
            3:       return 32'h00000040;  // SHUT_RST mode
            4:       return 32'h20000000;  // NOP
            default: return 32'h20000000;  // NOP fill
        endcase
    endfunction

    // ---- Timeout watchdog --------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n || state == IDLE) begin
            timeout_cnt <= '0;
            timeout     <= 1'b0;
        end else if (state != IDLE && state != PR_DONE && state != PR_ERROR) begin
            if (timeout_cnt < PR_TIMEOUT_CYC)
                timeout_cnt <= timeout_cnt + 1;
            else
                timeout <= 1'b1;
        end
    end

    // ---- FSM Next-State Logic ----------------------------------------------
    always_comb begin
        next = state;
        case (state)
            IDLE:     if (pr_trigger)         next = PR_INIT;
            PR_INIT:  if (icap_avail)         next = SENDING;
                      else if (timeout)       next = PR_ERROR;
            SENDING:  if (word_cnt == BITSTREAM_WORDS-1) next = VERIFY;
                      else if (timeout)       next = PR_ERROR;
            VERIFY:   if (!timeout)           next = PR_DONE;
                      else                    next = PR_ERROR;
            PR_DONE:                          next = IDLE;   // Auto-return to IDLE
            PR_ERROR:                         next = PR_ERROR; // Sticky, needs reset
            default:                          next = IDLE;
        endcase
    end

    // ---- FSM State Register ------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) state <= IDLE;
        else        state <= next;
    end

    // ---- Word counter (active during SENDING) ------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n || state == IDLE || state == PR_INIT)
            word_cnt <= '0;
        else if (state == SENDING && !icap_csn)
            word_cnt <= word_cnt + 1;
    end

    // ---- ICAP Interface Drives --------------------------------------------
    always_comb begin
        icap_csn   = 1'b1;  // Deasserted default
        icap_rdwrn = 1'b1;  // Read default
        icap_din   = 32'h20000000;  // NOP

        case (state)
            PR_INIT: begin
                icap_csn   = 1'b1;  // Deasserted during init
                icap_rdwrn = 1'b1;
            end
            SENDING: begin
                icap_csn   = 1'b0;  // Assert: writing configuration
                icap_rdwrn = 1'b0;
                icap_din   = get_bitstream_word(int'(word_cnt));
            end
            VERIFY: begin
                icap_csn   = 1'b0;
                icap_rdwrn = 1'b1;  // Read-back for CRC verify
            end
            default: begin
                icap_csn   = 1'b1;
                icap_rdwrn = 1'b1;
            end
        endcase
    end

    // ---- Output flags ------------------------------------------------------
    assign pr_busy        = (state != IDLE && state != PR_ERROR);
    assign pr_done        = (state == PR_DONE);
    assign pr_error       = (state == PR_ERROR);
    assign pr_state_debug = {5'b0, state};

endmodule
