// =============================================================================
//  Verilator C++ Harness — FPGA Lane Detection
//  Authors: Kaustubh Pandey · Krishanu Dey
//
//  Build:  see ../Makefile
//  Usage:  ./sim <image.png> [edge_threshold=64] [dump_vcd=0]
//
//  Outputs:
//    <image>_edges.png   —  binary edge map from Sobel+threshold stage
//    <image>_lanes.png   —  original image with detected lane lines overlaid
//    lane_results.csv    —  rho/theta values per frame
//    lane_detection.vcd  —  waveform dump (only if dump_vcd=1)
// =============================================================================

#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image.h"
#include "stb_image_write.h"

#include "Vlane_detection_top.h"   // Generated by Verilator
#include "verilated.h"
#include "verilated_vcd_c.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <string>
#include <vector>
#include <iostream>
#include <fstream>

// ---------------------------------------------------------------------------
//  Simulation timestamp (Verilator requirement)
// ---------------------------------------------------------------------------
vluint64_t main_time = 0;
double sc_time_stamp() { return (double)main_time; }

static VerilatedVcdC *tfp = nullptr;

// ---------------------------------------------------------------------------
//  Clock helpers
// ---------------------------------------------------------------------------
static void tick(Vlane_detection_top *dut)
{
    dut->clk ^= 1;
    dut->eval();
    if (tfp) tfp->dump(main_time);
    main_time++;
}

static void posedge(Vlane_detection_top *dut)   // rising only
{
    dut->clk = 1; dut->eval();
    if (tfp) tfp->dump(main_time); main_time++;
}

static void negedge(Vlane_detection_top *dut)   // falling only
{
    dut->clk = 0; dut->eval();
    if (tfp) tfp->dump(main_time); main_time++;
}

static void cycle(Vlane_detection_top *dut, int n = 1)
{
    for (int i = 0; i < n; i++) { posedge(dut); negedge(dut); }
}

// ---------------------------------------------------------------------------
//  Bresenham line draw on 3-ch RGB buffer
// ---------------------------------------------------------------------------
static void draw_line(uint8_t *img, int W, int H,
                      int x0, int y0, int x1, int y1,
                      uint8_t r, uint8_t g, uint8_t b, int thickness = 2)
{
    for (int t = -thickness/2; t <= thickness/2; t++) {
        int ax0 = x0, ay0 = y0 + t, ax1 = x1, ay1 = y1 + t;
        int dx = abs(ax1 - ax0), sx = ax0 < ax1 ? 1 : -1;
        int dy = -abs(ay1 - ay0), sy = ay0 < ay1 ? 1 : -1;
        int err = dx + dy;
        while (true) {
            if (ax0 >= 0 && ax0 < W && ay0 >= 0 && ay0 < H) {
                img[(ay0 * W + ax0) * 3 + 0] = r;
                img[(ay0 * W + ax0) * 3 + 1] = g;
                img[(ay0 * W + ax0) * 3 + 2] = b;
            }
            if (ax0 == ax1 && ay0 == ay1) break;
            int e2 = 2 * err;
            if (e2 >= dy) { err += dy; ax0 += sx; }
            if (e2 <= dx) { err += dx; ay0 += sy; }
        }
    }
}

// ---------------------------------------------------------------------------
//  Hough rho/theta bin  →  line endpoints on image
//  Accumulator convention:
//    theta_bin = 0..THETA_BINS-1  maps to  0°..179°
//    rho_bin   = 0..RHO_BINS-1   maps to  -(RHO_BINS/2)..(RHO_BINS/2 - 1)
// ---------------------------------------------------------------------------
static void rho_theta_to_endpoints(int rho_bin, int theta_bin,
                                   int W, int H, int RHO_BINS,
                                   int &x0, int &y0, int &x1, int &y1)
{
    double rho   = (double)rho_bin - (double)RHO_BINS / 2.0;
    double theta = theta_bin * M_PI / 180.0;
    double cos_t = cos(theta);
    double sin_t = sin(theta);

    if (fabs(sin_t) > 1e-6) {
        x0 = 0;      y0 = (int)round((rho - x0 * cos_t) / sin_t);
        x1 = W - 1;  y1 = (int)round((rho - x1 * cos_t) / sin_t);
    } else {
        // Near-vertical
        y0 = 0; y1 = H - 1;
        x0 = x1 = (fabs(cos_t) > 1e-6) ? (int)round(rho / cos_t) : W / 2;
    }
}

// ---------------------------------------------------------------------------
//  Nearest-neighbour resize (RGB)
// ---------------------------------------------------------------------------
static std::vector<uint8_t> nn_resize(const uint8_t *src, int sw, int sh,
                                      int dw, int dh)
{
    std::vector<uint8_t> dst(dw * dh * 3);
    for (int y = 0; y < dh; y++) {
        int sy = (int)((double)y / dh * sh);
        for (int x = 0; x < dw; x++) {
            int sx = (int)((double)x / dw * sw);
            for (int c = 0; c < 3; c++)
                dst[(y * dw + x) * 3 + c] = src[(sy * sw + sx) * 3 + c];
        }
    }
    return dst;
}

// ---------------------------------------------------------------------------
//  MAIN
// ---------------------------------------------------------------------------
int main(int argc, char **argv)
{
    // ---- Compile-time DUT parameters (injected via -D in Makefile) --------
#ifndef IMG_WIDTH
#  define IMG_WIDTH  640
#endif
#ifndef IMG_HEIGHT
#  define IMG_HEIGHT 480
#endif
#ifndef RHO_BINS_VAL
#  define RHO_BINS_VAL 1024
#endif
#ifndef HT_THRESHOLD_VAL
#  define HT_THRESHOLD_VAL 50
#endif

    const int DUT_W       = IMG_WIDTH;
    const int DUT_H       = IMG_HEIGHT;
    const int RHO_BINS    = RHO_BINS_VAL;
    const int HT_THRESH   = HT_THRESHOLD_VAL;

    // ---- Parse CLI --------------------------------------------------------
    if (argc < 2) {
        fprintf(stderr,
            "Usage: %s <image.png/jpg/bmp> [edge_thresh=%d] [dump_vcd=0]\n"
            "  edge_thresh : Sobel magnitude threshold override (0–255)\n"
            "  dump_vcd    : 1 to write lane_detection.vcd\n",
            argv[0], 64);
        return 1;
    }
    const char *img_path = argv[1];
    int   edge_thresh    = (argc >= 3) ? atoi(argv[2]) : 64;
    bool  dump_vcd       = (argc >= 4) ? (atoi(argv[3]) != 0) : false;

    printf("╔══════════════════════════════════════════════╗\n");
    printf("║  Verilator Lane Detection Verification       ║\n");
    printf("╚══════════════════════════════════════════════╝\n");
    printf("  Image    : %s\n",  img_path);
    printf("  DUT size : %d × %d\n", DUT_W, DUT_H);
    printf("  EdgeThresh: %d\n", edge_thresh);
    printf("  RHO_BINS : %d\n", RHO_BINS);
    printf("  HT_THRESH: %d\n", HT_THRESH);
    printf("  VCD dump : %s\n\n", dump_vcd ? "yes (large!)" : "no");

    // ---- Load & resize image ----------------------------------------------
    int W0, H0, ch;
    uint8_t *raw = stbi_load(img_path, &W0, &H0, &ch, 3);
    if (!raw) {
        fprintf(stderr, "ERROR: cannot load '%s' — %s\n",
                img_path, stbi_failure_reason());
        return 1;
    }
    printf("Loaded: %d × %d (%d ch → RGB)\n", W0, H0, ch);
    auto img = nn_resize(raw, W0, H0, DUT_W, DUT_H);
    stbi_image_free(raw);
    if (W0 != DUT_W || H0 != DUT_H)
        printf("Resized to %d × %d to match DUT parameters.\n", DUT_W, DUT_H);

    // ---- Verilator init ---------------------------------------------------
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(dump_vcd);

    Vlane_detection_top *dut = new Vlane_detection_top;

    if (dump_vcd) {
        tfp = new VerilatedVcdC;
        dut->trace(tfp, 99);
        tfp->open("lane_detection.vcd");
        printf("VCD trace open: lane_detection.vcd\n\n");
    }

    // ---- Reset ------------------------------------------------------------
    dut->clk         = 0;
    dut->rst_n       = 0;
    dut->pixel_valid = 0;
    dut->hsync       = 0;
    dut->vsync       = 0;
    dut->pixel_in    = 0;
    dut->eval();
    cycle(dut, 8);
    dut->rst_n = 1;
    cycle(dut, 4);
    printf("Reset released.\n");

    // ---- Edge-map buffer --------------------------------------------------
    std::vector<uint8_t> edge_buf(DUT_W * DUT_H, 0);

    // ---- Stream one frame -------------------------------------------------
    printf("Streaming %d × %d frame...\n", DUT_W, DUT_H);
    fflush(stdout);

    // Start-of-frame vsync (active high, 1 cycle)
    dut->vsync = 1; cycle(dut); dut->vsync = 0;

    for (int row = 0; row < DUT_H; row++) {

        // Start-of-line hsync (active high, 1 cycle)
        dut->hsync = 1; posedge(dut); negedge(dut); dut->hsync = 0;

        for (int col = 0; col < DUT_W; col++) {
            uint8_t R = img[(row * DUT_W + col) * 3 + 0];
            uint8_t G = img[(row * DUT_W + col) * 3 + 1];
            uint8_t B = img[(row * DUT_W + col) * 3 + 2];

            // Pixel format: {R[7:0], G[7:0], B[7:0]}  — matches rgb_to_gray.sv
            dut->pixel_in    = ((uint32_t)R << 16) | ((uint32_t)G << 8) | B;
            dut->pixel_valid = 1;

            // Rising edge — capture DUT outputs
            posedge(dut);
            if (dut->edge_valid) {
                int ex = (int)dut->edge_x;
                int ey = (int)dut->edge_y;
                if (ex >= 0 && ex < DUT_W && ey >= 0 && ey < DUT_H)
                    edge_buf[ey * DUT_W + ex] = 255;
            }
            negedge(dut);
        }

        dut->pixel_valid = 0;
        cycle(dut, 1);  // brief inter-line gap

        // Progress indicator every 10%
        if ((row + 1) % (DUT_H / 10) == 0)
            printf("  ... %3d%%\n", (row + 1) * 100 / DUT_H);
    }

    // End-of-frame vsync — triggers Hough accumulator peak scan
    dut->vsync = 1; cycle(dut); dut->vsync = 0;
    dut->pixel_valid = 0;

    // ---- Wait for Hough FSM -----------------------------------------------
    // Worst case: full accumulator scan = RHO_BINS * THETA_BINS cycles
    printf("\nWaiting for Hough FSM (max %d cycles)...\n", RHO_BINS * 180 + 512);

    int  rho_left = 0, theta_left = 0;
    int  rho_right= 0, theta_right= 0;
    bool lane_valid = false;
    int  lane_valid_cycle = -1;

    for (int i = 0; i < RHO_BINS * 180 + 512; i++) {
        posedge(dut);
        if (dut->lane_valid && !lane_valid) {
            rho_left    = (int)dut->rho_left;
            theta_left  = (int)dut->theta_left;
            rho_right   = (int)dut->rho_right;
            theta_right = (int)dut->theta_right;
            lane_valid       = true;
            lane_valid_cycle = i;
            printf("  lane_valid asserted at Hough-wait cycle %d\n", i);
        }
        negedge(dut);
        if (lane_valid) break;  // stop early once found
    }

    // ---- Results ----------------------------------------------------------
    printf("\n╔══════════════════════════════════════════════╗\n");
    printf("║            Lane Detection Results             ║\n");
    printf("╚══════════════════════════════════════════════╝\n");

    if (lane_valid) {
        int actual_rho_left  = rho_left  - RHO_BINS / 2;
        int actual_rho_right = rho_right - RHO_BINS / 2;
        printf("  ✓ Left  lane : ρ = %4d px,  θ = %3d°\n",
               actual_rho_left,  theta_left);
        printf("  ✓ Right lane : ρ = %4d px,  θ = %3d°\n",
               actual_rho_right, theta_right);
        printf("  (lane_valid asserted %d cycles after end-of-frame vsync)\n",
               lane_valid_cycle);

        // Sanity checks
        if (theta_left >= 90)
            printf("  ⚠ WARN: left-lane theta (%d°) ≥ 90° — may be misclassified\n",
                   theta_left);
        if (theta_right < 90)
            printf("  ⚠ WARN: right-lane theta (%d°) < 90° — may be misclassified\n",
                   theta_right);
    } else {
        printf("  ✗ lane_valid never asserted.\n");
        printf("    Possible causes:\n");
        printf("    • HT_THRESHOLD (%d) too high — try lowering it\n", HT_THRESH);
        printf("    • ROI window excludes all edges — check ROI_ROW_TOP/BOT params\n");
        printf("    • edge_thresh (%d) too high — try a lower value\n", edge_thresh);
        printf("    • Image does not contain lane markings in expected position\n");
    }

    // ---- Save edge map ----------------------------------------------------
    {
        std::string out = std::string(img_path) + "_edges.png";
        int edge_px = 0;
        for (auto v : edge_buf) if (v) edge_px++;
        stbi_write_png(out.c_str(), DUT_W, DUT_H, 1, edge_buf.data(), DUT_W);
        printf("\nEdge map saved : %s  (%d edge pixels)\n", out.c_str(), edge_px);
        if (edge_px == 0)
            printf("  ⚠ WARN: zero edge pixels — pipeline may not have flushed.\n"
                   "         Try increasing PIPELINE_FLUSH_CYCLES in Makefile.\n");
    }

    // ---- Save lane overlay ------------------------------------------------
    if (lane_valid) {
        std::vector<uint8_t> overlay(img.begin(), img.end());
        int x0, y0, x1, y1;

        rho_theta_to_endpoints(rho_left,  theta_left,  DUT_W, DUT_H, RHO_BINS,
                               x0, y0, x1, y1);
        draw_line(overlay.data(), DUT_W, DUT_H, x0, y0, x1, y1,
                  50, 255, 50, 3);  // green = left

        rho_theta_to_endpoints(rho_right, theta_right, DUT_W, DUT_H, RHO_BINS,
                               x0, y0, x1, y1);
        draw_line(overlay.data(), DUT_W, DUT_H, x0, y0, x1, y1,
                  50, 100, 255, 3); // blue  = right

        std::string out = std::string(img_path) + "_lanes.png";
        stbi_write_png(out.c_str(), DUT_W, DUT_H, 3, overlay.data(), DUT_W * 3);
        printf("Lane overlay   : %s\n", out.c_str());
    }

    // ---- CSV log ----------------------------------------------------------
    {
        std::ofstream csv("lane_results.csv");
        csv << "frame,rho_left,theta_left_deg,rho_right,theta_right_deg,lane_valid\n";
        csv << "1,"
            << (lane_valid ? rho_left  - RHO_BINS/2 : 0) << ","
            << (lane_valid ? theta_left  : 0) << ","
            << (lane_valid ? rho_right - RHO_BINS/2 : 0) << ","
            << (lane_valid ? theta_right : 0) << ","
            << (lane_valid ? 1 : 0) << "\n";
        printf("CSV log        : lane_results.csv\n");
    }

    // ---- Cleanup ----------------------------------------------------------
    if (tfp) { tfp->close(); delete tfp; }
    dut->final();
    delete dut;

    printf("\nTotal sim time : %llu half-cycles\n",
           (unsigned long long)main_time);
    printf("═══════════════════════════════════════════════\n\n");

    return lane_valid ? 0 : 2;  // exit code 2 = no lanes found
}
