// =============================================================================
// File        : tb_verilator.cpp
// Project     : Supply Chain Security in 3PIP FPGA
// Author      : Kaustubh Pandey (230959054)
// Description : Verilator C++ harness for security_top.
//               Mirrors the 4-phase stimulus from tb_security_top.sv
//               but drives the DUT through generated C++ model.
//               Produces: security_top_verilator.vcd for GTKWave.
//
// Build:  make          (from project root — uses the Makefile)
// Manual: verilator --sv --cc --exe --trace --timing -Wall \
//           --top-module security_top \
//           -CFLAGS "-O2 -std=c++17" \
//           -o Vsecurity_top --Mdir build_verilator \
//           rtl/*.sv tb/tb_verilator.cpp
//         make -C build_verilator -f Vsecurity_top.mk Vsecurity_top
//         ./build_verilator/Vsecurity_top
// =============================================================================

#include "Vsecurity_top.h"        // Generated by Verilator from security_top.sv
#include "verilated.h"
#include "verilated_vcd_c.h"      // VCD waveform output
#include <cstdio>
#include <cstdint>
#include <cstdlib>

// ── Simulation time (picoseconds) ────────────────────────────────
static uint64_t sim_time = 0;

// ── Test counters ─────────────────────────────────────────────────
static int pass_cnt = 0;
static int fail_cnt = 0;

// ── Clock helper: advance one full clock cycle (10 ns @ 100 MHz) ─
void tick(Vsecurity_top* dut, VerilatedVcdC* vcd) {
    // Rising edge
    dut->clk = 1;
    dut->eval();
    if (vcd) vcd->dump(sim_time += 5000);   // 5 ns = 5000 ps

    // Falling edge
    dut->clk = 0;
    dut->eval();
    if (vcd) vcd->dump(sim_time += 5000);
}

// ── Self-checking assertion ───────────────────────────────────────
void check(const char* name, int expected, int got) {
    if (expected == got) {
        printf("[PASS] %s\n", name);
        pass_cnt++;
    } else {
        printf("[FAIL] %s: expected=%d  got=%d\n", name, expected, got);
        fail_cnt++;
    }
}

// ═════════════════════════════════════════════════════════════════
int main(int argc, char** argv) {

    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);   // Enable VCD tracing

    // Instantiate DUT (generated class from security_top.sv)
    Vsecurity_top* dut = new Vsecurity_top;

    // Attach VCD tracer
    VerilatedVcdC* vcd = new VerilatedVcdC;
    dut->trace(vcd, 99);                              // Trace all signals
    vcd->open("security_top_verilator.vcd");

    printf("============================================================\n");
    printf("  Verilator Simulation — Supply Chain Security 3PIP FPGA   \n");
    printf("  Kaustubh Pandey (230959054) | MIT Manipal ECE 4424        \n");
    printf("============================================================\n\n");

    // ── PHASE 0: Reset & RO Calibration ──────────────────────────
    printf("=== PHASE 0: Reset & RO Calibration ===\n");

    dut->rst_n       = 0;
    dut->valid_in    = 0;
    dut->acc_clr     = 0;
    dut->a           = 0;
    dut->b           = 0;
    dut->cal_en      = 1;     // Enter calibration mode
    dut->ro_sample_en = 0;
    dut->icap_avail  = 1;     // ICAP always ready in simulation

    // Hold reset for 10 cycles
    for (int i = 0; i < 10; i++) tick(dut, vcd);
    dut->rst_n = 1;
    for (int i = 0; i < 5; i++) tick(dut, vcd);

    // Calibration window: run 1200 cycles with benign patterns
    dut->ro_sample_en = 1;
    for (int i = 0; i < 1200; i++) {
        dut->valid_in = (i % 3 != 0) ? 1 : 0;   // Intermittent valid
        dut->a = 0x0101;
        dut->b = 0x0001;
        tick(dut, vcd);
    }
    dut->ro_sample_en = 0;
    dut->cal_en       = 0;
    dut->valid_in     = 0;
    for (int i = 0; i < 20; i++) tick(dut, vcd);

    check("Phase0: No alarm during calibration", 0, (int)dut->global_alarm);
    printf("    conf_score after calibration: %d\n", dut->conf_score);

    // ── PHASE 1: Normal Operation ─────────────────────────────────
    printf("\n=== PHASE 1: Normal Operation — Expect No Alarm ===\n");

    // Safe operands: a[15:12] = 0x0 ≠ 0xA → Trojan trigger counter stays 0
    for (int i = 0; i < 500; i++) {
        dut->valid_in = 1;
        dut->a = 0x0505;   // MSB nibble = 0x0
        dut->b = 0x0303;
        tick(dut, vcd);
    }
    dut->valid_in = 0;
    for (int i = 0; i < 50; i++) tick(dut, vcd);

    check("Phase1: No false-positive alarm",  0, (int)dut->global_alarm);
    check("Phase1: PR controller idle",       0, (int)dut->pr_busy);
    printf("    conf_score (should be 0): %d\n", dut->conf_score);

    // ── PHASE 2: Arm Trojan (1025 trigger patterns) ───────────────
    printf("\n=== PHASE 2: Trojan Arming — 1025 Trigger Patterns ===\n");

    // a[15:12] = 0xA triggers the Trojan counter in mac_trojan.sv
    for (int i = 0; i < 1025; i++) {
        dut->valid_in = 1;
        dut->a = 0xA001;   // 1010_0000_0000_0001 → nibble[15:12] = 0xA
        dut->b = 0x0001;
        tick(dut, vcd);
    }
    dut->valid_in = 0;
    for (int i = 0; i < 20; i++) tick(dut, vcd);

    printf("    After arming: global_alarm=%d  conf_score=%d\n",
           (int)dut->global_alarm, (int)dut->conf_score);
    // Trojan armed but payload not active until next valid cycle — alarm should still be 0

    // ── PHASE 3: Payload Active — Detection & Recovery ────────────
    printf("\n=== PHASE 3: Payload Active — Detection & Recovery ===\n");

    dut->ro_sample_en = 1;
    int alarm_cycle = -1;

    for (int i = 0; i < 2000; i++) {
        dut->valid_in = (i % 4 != 0) ? 1 : 0;
        dut->a = 0xA0FF;    // Keep trigger pattern; Trojan active → MSB flip
        dut->b = 0x0100;
        tick(dut, vcd);

        if (dut->global_alarm && alarm_cycle < 0) {
            alarm_cycle = i;
            printf("    global_alarm FIRED at cycle %d (Phase 3 offset)\n", i);
        }
    }
    dut->ro_sample_en = 0;
    dut->valid_in     = 0;

    check("Phase3: TMR alarm triggered",      1, alarm_cycle >= 0 ? 1 : 0);
    check("Phase3: Global alarm latched",     1, (int)dut->global_alarm);
    printf("    conf_score: %d (expect >= 4)\n", (int)dut->conf_score);
    printf("    alarm_status: 0x%02X\n",          (unsigned)dut->alarm_status);
    printf("    pr_busy: %d\n",                   (int)dut->pr_busy);

    // Wait for PR controller to complete bitstream reload
    printf("\n    Waiting for PR recovery (~4352 cycles)...\n");
    for (int i = 0; i < 5500; i++) tick(dut, vcd);

    check("Phase3: PR done after recovery",   1, (int)dut->pr_done | (dut->pr_busy == 0));
    printf("    icap_csn: %d  icap_rdwrn: %d\n",
           (int)dut->icap_csn, (int)dut->icap_rdwrn);

    // ── Final results ─────────────────────────────────────────────
    printf("\n============================================================\n");
    printf("  RESULTS: %d PASSED | %d FAILED\n", pass_cnt, fail_cnt);
    printf("  VCD waveform: security_top_verilator.vcd\n");
    printf("  View with:    gtkwave security_top_verilator.vcd\n");
    printf("============================================================\n");

    if (fail_cnt == 0)
        printf("  ✔ ALL TESTS PASSED — Security framework validated\n\n");
    else
        printf("  ✗ FAILURES DETECTED — Review signals in GTKWave\n\n");

    vcd->close();
    delete vcd;
    delete dut;
    return fail_cnt > 0 ? EXIT_FAILURE : EXIT_SUCCESS;
}
